# Generated by Django 4.1.3 on 2023-04-30 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("score", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulargameseed",
            name="bowler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="regulargamescore",
            name="bowler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="regulargamescore",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="score.regulargamedate"
            ),
        ),
        migrations.AddField(
            model_name="monthscore",
            name="bowler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
