# Generated by Django 4.1.3 on 2022-11-08 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("score", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulargamescore",
            name="first",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="regulargamescore",
            name="fourth",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="regulargamescore",
            name="second",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="regulargamescore",
            name="third",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SeedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.DateField()),
                (
                    "seed",
                    models.IntegerField(
                        choices=[
                            (1, "First Seed"),
                            (2, "Second Seed"),
                            (3, "Third Seed"),
                            (4, "Fourth Seed"),
                            (5, "Fifth Seed"),
                            (6, "Sixth Seed"),
                        ]
                    ),
                ),
                (
                    "bowler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
